# Site settings
title: Sacred Seed Studio
description: > # A indie game development studio location in Canada, eh.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.sacredseedstudio.com" # the base hostname & protocol for your site

# Contact info
twitter_username: sacredseedstdio
github_username:  sacredseedstudio
email: sacredseedstudio@gmail.com

# Blog settings
permalink: /blog/:year/:month/:day/:title
paginate: 6
paginate_path: "/blog/page/:num"

# Navigation
navigation:
- text: Games
  url: /games/
  nav_layout: game
- text: Blog
  url: /blog/
  nav_layout: blog

game_types:
  hackathon
  gamejam
  release
  experiment

# Build settings
markdown: kramdown
jekyll-minifier:
  exclude: 'feed.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns

# Plugins
gems:
- jekyll-paginate
- jekyll-minifier

# Development
host: 0.0.0.0
